### ISSUE TITLE
Skip link checks in code blocks

### ISSUE THREAD

**Issue by borekb** [TomasHubelbauer/vscode-markdown-link-suggestions#1]
For example:

~~~md
I'm writing some `[example](example.md)` of a link syntax.
That example.md should not be checked for existence on the disk.

Same for code blocks:

```md
Some [example](example.md) here.
```

~~~

**Comment by TomasHubelbauer** [comment]
I've published a new version, 7.0.2, today. It addresses this issue in a crude way (recognizing code blocks in this extension as opposed in the MarkDown parsing library), but should fix this. Eventually, I will improve the MarkDown parser enough to be able to remove the hack in this extension and rely solely on its output.

Please check the new version out and let me know if it works for you. Any other feedback I am also all ears about.

**Comment by borekb** [comment]
Thanks for the effort. I reported based on this case:

https://github.com/versionpress/versionpress/blame/master/docs/README.md#L21

I still get a warning there:

![image](https://user-images.githubusercontent.com/101152/42968875-db9fb7d0-8ba4-11e8-87bd-b2634f7d0061.png)

**Comment by TomasHubelbauer** [comment]
Right, I only covered off code blocks, not inline code spans for now. I will continue on with that, that should be even easier to support (just lookbehind and lookahead on the regex).

**Comment by TomasHubelbauer** [comment]
7.0.3 I just released should correctly ignore links in both kinds of MarkDown code elements.

**Comment by borekb** [comment]
🎉 , it works!
